version: '3.1'

services:
  wordpress:
    build: .
    image: peakresponse/peak-blog
    restart: always
    ports:
      - ${HOST_PORT:-8080}:80
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html
  db:
    image: mariadb:10.5.5
    restart: always
    env_file:
      - .env
    volumes:
      - db:/var/lib/mysql
volumes:
  wordpress:
  db:
